### ISSUE TITLE
Readme documentation update

### ISSUE THREAD

**Issue by 0xFounders** [undeflife/libreoffice-rs#16]
When trying to run the sample for saving an openxml document to pdf on Ubuntu 22.04 I was receiving an application error
After installing the package, libreoffice-writer, I was able to successfully convert my docx to pdf.
I believe this package should also be added to the documentation as an installation.

**Comment by undeflife** [comment]
i believe libreoffice-core libreofficekit-dev is enough, perhaps i would look into this in  a clean env  later.
