### ISSUE TITLE
Dealing with password-protected documents

### ISSUE THREAD

**Issue by yveszoundi** [undeflife/libreoffice-rs#2]
Is it possible to provide an example for the `registerCallback` function, for example providing a document password?

- I don't have much knowledge of C/C++ and can't figure out how to do it
- As it pertain to the LibreOffice callback themselves it seems that there would be 2 callbacks fired (https://github.com/LibreOffice/core/blob/master/include/LibreOfficeKit/LibreOfficeKitEnums.h#L931)

If it's possible to leverage callbacks for providing passwords, then I believe that it's a very flexible option.

### Possible alternative
I think that it could work by implementing the "setDocumentPassword" LibreOfficeKit method: https://github.com/LibreOffice/core/blob/master/include/LibreOfficeKit/LibreOfficeKit.hxx#L993.
I tried a naive implementation based on existing `libreoffice-rs` code, but it crashed with "Application Error".

### My use-case
My end goal is to replace direct command-line calls against the LibreOffice binary in [my application](https://github.com/rimerosolutions/entrusted), as I  can't easily deal with password protected documents.

- Preferably, I would like an equivalent of [Apache POI](https://poi.apache.org/) in Rust, but POI has been around for a very long time. `libreoffice-rs` appears to be the most viable option in comparison to "unoconv*" or immature free libraries.
- I previously tried integrating Rust with Java (Apache POI) without embedding a JVM (Graalvm native image and Rust bindings to exposed "shared library symbols"): I got lucky once but it was a bit involved.. (~100MB for just PPT/PPTX support)

**Comment by undeflife** [comment]
> Is it possible to provide an example for the registerCallback function, for example providing a document password?

I'm not sure how to implement this too.
according to [callback type definition](https://github.com/LibreOffice/core/blob/master/include/LibreOfficeKit/LibreOfficeKitTypes.h#L20) I guess you should implement a Rust Function which used keyword `extern "C"` and then pass it as a raw pointer to `registerCallback`

> I think that it could work by implementing the "setDocumentPassword" LibreOfficeKit method: https://github.com/LibreOffice/core/blob/master/include/LibreOfficeKit/LibreOfficeKit.hxx#L993.
I tried a naive implementation based on existing libreoffice-rs code, but it crashed with "Application Error".

I can add `setDocumentPassword` in  later release,  for now your can `get_error()` to see the actual error which causes LibreOffice crashed.

**Comment by yveszoundi** [comment]
Thanks, I'll keep trying out couple of things and learn more about _ffi_ in general.

### About registerCallback
Indeed for the your point about `registerCallback`, I think that some kind of shim with the `extern "C"` needs implementation similarly to how [fltk-rs](https://github.com/fltk-rs/fltk-rs/) interacts with some C libraries: https://github.com/fltk-rs/fltk-rs/blob/e1cc963680ca729b4b293f1e363f879b791c0cea/fltk/src/menu.rs#L662

I think that the _LibreOfficeKitCallback_ is a _typedef_ with 3 params, I'll keep investigating the magic that needs to happen (c_void stuff, possibly "transmutation", etc.)


### My initial attempts for setDocumentPassword
I don't get to capture details about the error itself, as _LibreOfficeKit_ crashes prior that.

```rust
    pub fn set_document_password(&mut self, url: &str, password: &str) -> Result<(), Error> {
        let c_url = CString::new(url).unwrap();
        let c_password = CString::new(password).unwrap();

        unsafe {
            // The crash seems to happen here
            (*self.lok_clz).setDocumentPassword.unwrap()(self.lok, c_url.as_ptr(), c_password.as_ptr());
            let error = self.get_error();

            if error != "" {
                return Err(Error::new(error));
            }
        }

        Ok(())
    }
```

**Comment by undeflife** [comment]
> I think that some kind of shim with the extern "C" needs implementation similarly to how [fltk-rs](https://github.com/fltk-rs/fltk-rs/) interacts with some C libraries: https://github.com/fltk-rs/fltk-rs/blob/e1cc963680ca729b4b293f1e363f879b791c0cea/fltk/src/menu.rs#L662

yes, this link sets a good example of callback-based C FFI .


>I don't get to capture details about the error itself, as LibreOfficeKit crashes prior that.

I have tried this myself:

- Load a password-protectd document , LibreOffice throws error unsupport URI.
- set_document_password before loading, LibreOffice crashes without any detail message.

The only option left open to us is try register callback.

**Comment by yveszoundi** [comment]
I made some "relative" progress based on the documentation that you added for `set_document_password` and  random experiments. My current understanding is that the following needs to happen:

- Enable some optional features to load password-protected documents
- Register a callback (seems that I'm missing maybe something minor, per last section of this document)
- Set the document password for a given URL within the callback (based on the callback type or payload?)

### A) Implementing setOptionalFeatures
Apparently the password functionality [requires some optional features to be enabled](https://cgit.freedesktop.org/libreoffice/core/commit/?id=43f5161991cffedabb280a6e4e388c5bcbac4f96):

- https://github.com/LibreOffice/core/blob/master/include/LibreOfficeKit/LibreOfficeKit.h#L79
- https://github.com/LibreOffice/core/blob/master/include/LibreOfficeKit/LibreOfficeKitEnums.h#L75

I didn't bother yet creating an enum matching relevant `LibreOfficeKitEnums` values.
```rust
    pub fn set_optional_features(&mut self, feature_flags: u64) -> Result<(), Error> {
        
        unsafe {
            let doc = (*self.lok_clz).setOptionalFeatures.unwrap()(self.lok, feature_flags);
            let error = self.get_error();
            if error != "" {
                return Err(Error::new(error));
            }
            Ok(())
        }
    }
```
### B) Re-implement register_callback for convenience

This is based on the `fltk-rs` example and I'm able to receive a callback, not sure if I got it all correctly though

```rust
pub fn register_callback<F: FnMut(i32, String)  + 'static> (&mut self, cb: F) -> Result<(), Error> {
        unsafe {
            //LibreOfficeKitCallback typedef (int nType, const char* pPayload, void* pData);
            unsafe extern "C" fn shim(n_type: i32, payload: *const std::os::raw::c_char, data: *mut std::os::raw::c_void) {
                let a: *mut Box<dyn FnMut()> = data as *mut Box<dyn FnMut()>;
                let f: &mut (dyn FnMut()) = &mut **a;
                let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(f));
            }
            let a: *mut Box<dyn FnMut(i32, String) > = Box::into_raw(Box::new(Box::new(cb)));
            let data: *mut std::os::raw::c_void = a as *mut std::ffi::c_void;
            let callback: LibreOfficeKitCallback = Some(shim);
            (*self.lok_clz).registerCallback.unwrap()(self.lok, callback, data);

            let error = self.get_error();
            if error != "" {
                return Err(Error::new(error));
            }
        }

        Ok(())
    }
```

### C) Sample usage

It seems that I'm able to successfully invoke `set_document_password`, but I then get an `munmap_chunk(): invalid pointer error`. I suspect that it's due to uninitialized data (cloning a office instance) or missing logic in my `register_callback` implementation...  

#### The code

```rust
use libreoffice_rs::Office;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let url = "/home/vip/Tests/test.odt";
    let password = "test";
    
    let mut office = Office::new("/usr/lib/libreoffice/program")?;
    office.set_optional_features(1)?;

    office.register_callback({
        // Derived clone to use the Office object instance inside the closure
        let mut office = office.clone();

        move |ntype, payload| {
            println!("ntype: {:?}, payload: {:?}", ntype, payload);
            // apparently libreofficekit wants a file URI and no a regular file path
            let ret = office.set_document_password("file:///home/vip/Tests/test.odt", password);
            println!("We are able to call set_document_password...: {:?}", ret);
        }
    });

    let mut doc = office.document_load(url)?;

    doc.save_as("/home/vip/Tests/doctest.pdf", "pdf", None);

    Ok(())
}
```
#### The error message

```text
No language allowlisted, turning off the language support.
ntype: -243246672, payload: ""PH�<$��"
﻿﻿﻿﻿﻿﻿﻿﻿We are able to call set_document_password...: Ok(())
munmap_chunk(): invalid pointer
Unspecified Application Error
```

**Comment by yveszoundi** [comment]
@undeflife , I figured it out and I'm preparing a pull request for the initial implementation.

**Comment by undeflife** [comment]
Great work!

By the way if you like create enums from `LibreOfficeKitEnums` can just simply add `#include "LibreOfficeKit/LibreOfficeKitEnums.h"` to `wrapper.h`,  bindgen will do the rest.

**Comment by yveszoundi** [comment]
Notes about the above pull-request 

- I was not able to get the `LibreOfficeKitEnums` to generate automatically, I supposed that it's related to `if defined` "macros" and how they need to be handled with `bindgen`.
- I cannot yet differentiate properly the callback types: no rust enums and possibly lack of clarity about received values but this could just be a misunderstanding about how data should be cast). This will important to address as people need access to other features.
