### ISSUE TITLE
Enhancement - Type safe input URLs for few methods

### ISSUE THREAD

**Issue by yveszoundi** [undeflife/libreoffice-rs#5]
### Problem statement 

Sometimes LibreOfficeKit expects a file URL instead of a regular path (`set_document_password`, `unset_document_password` that will exist in a future pull request). There are also instances where LibreOfficeKit methods accept both a normal path as well as a file URL...

- It feels better to make it explicit to developers from a design perspective
- It feels like it will reduce ambiguity and usage errors

#### Approach
- Create a new `FileUri` structs that will encapsulate and absolute file URI (underlying string): 
  - A `FileUri` can be constructed
  - A `FileUri` is guaranteed of correctness upon construction (path existence check)
  - A `FileUri` implements display to return the expected path URL with the `file` scheme
- Update few methods to accept a `FileUri` instead of a plain `&str` type
  - `document_load`
  - `document_load_with`
  - `set_document_password`
  - `unset_document_password` (addition via future pull request)

#### Other considerations
- Maybe just prepending blindly "file:/" in front of absolute paths is good enough for LibreOfficeKit and there's no need for additional dependencies
- For robustness, this would likely need a new dependency. 
  - [uriparse](https://crates.io/crates/uriparse) seems reasonably simple and good enough (**_preferred_**)
  - [There are few options](https://crates.io/search?q=uri) some of them pull several transitive dependencies and the quality might vary
- Alternatively, the status-quo doesn't hurt either. 
  - Assuming that developers pay attention to the docs, they will know that some of the paths are expected to be valid file URIs.
  - Developers can pull themselves additional libraries or prefix directly file paths accordingly with a file URL scheme

**Comment by undeflife** [comment]
As i known,  LibreOfficeKit always expects a URL except `install_path` which passing to lok_init, and `load_document` can accpet an encoded URL to load a remote file. 

so if we introduce a new type like `FileUri` it should not only support file schema but also http(maybe ftp too), then this `FileUri` is kind overcomplex.

**Comment by yveszoundi** [comment]
> so if we introduce a new type like FileUri it should not only support file schema but also http(maybe ftp too), then this FileUri is kind overcomplex.

Totally agree, it makes sense to keep things simple.

This is what I came up with: sadly my implementation relies on the [url](https://crates.io/crates/url) crate, for "basic" robustness. Maybe there's no real need to make any change at this point in time, what do you think?

```rust
use std::error::Error;

pub mod docurls {

    use std::fmt;
    use std::path::Path;
    use url::Url;
    use std::error::Error;

    #[derive(Debug, Clone)]
    pub struct DocUrl(String);

    impl fmt::Display for DocUrl {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(f, "{}", self.0)
        }
    }

    pub fn local<S: Into<String>>(path: S) -> Result<DocUrl, Box<dyn Error>> {
        let uri_location = path.into();
        let p = Path::new(&uri_location);

        if !p.is_absolute() {
            return Err(format!("The path {} must be absolute!", &uri_location).into());
        }

        let url_ret = Url::from_file_path(&uri_location);

        match url_ret {
            Ok(url_value) => {                
                Ok(DocUrl(url_value.as_str().to_owned()))
            },
            Err(ex) => {
                return Err(format!("Failed to parse as URL {}! {:?}", uri_location, ex).into());
                
            }
        }
    }

    pub fn remote<S: Into<String>>(uri: S) -> Result<DocUrl, Box<dyn Error>> {
        let uri_location = uri.into();
        let uri_location_str = uri_location.as_str();

        if let Err(ex) = Url::parse(uri_location_str) {
            return Err(format!("Failed to parse URI {}! {}", uri_location, ex.to_string()).into());
        }

        Ok(DocUrl(uri_location))
    }
}

fn main() -> Result<(), Box<dyn Error>> {
    let location_local = "/home/vip/experiments/Cargo.toml";
    println!("File URL: {}", docurls::local(location_local)?.to_string());

    let location_remote = "https://www.google.com/";
    println!("Remote URL: {}", docurls::remote(location_remote)?.to_string());

    Ok(())
}
```

**Comment by undeflife** [comment]
Looks Ok to me, I thinnk i can live with this one extra dependency.
